
=pod

=encoding utf-8

=head1 Name

libTest.sh

=head1 Description

Test library. aide à tester le comportement d un script dans un environnement maitrise.

=head1 Dependencies

libError.sh

=head1 Functions

=head2 assert_return_code

assert_return_code "COMMAND" "EXPECTED_RETURN_CODE"

 RETURN 0 if EXPECTED_RETURN_CODE == RETURN_CODE
 RETURN 1 othewise

in both case there are a message of type

B<hostname - date time - program -(function_tested) return_code;expected_return_code state>

tel que :

myhost - 0211 15:39 - :  ./test.sh -(ls) code retour:0 ; attendu:1  KO 

=head2 assert_return_err

TODO : verify stderr

=head2 assert_return_message

TODO : verify stdout

=head1 Author

Grillon

=cut
