=pod

=head1 Name

libsh

=head1 Description

I'm often doing librairies for my shell scripts and repeating myself.
This if an attempt to capitalize.

=head1 Content

a general librairy. I did it few years ago in ksh and I don't know if it works in bash.
I like the debug and erreur fonctions and would like to reuse them without copy past.

=head1 TODO

=over 1

=item *

test in bash

=item *

clean useless functions

=item *

document usefull functions

=back

=head1 Author

Grillon

=cut
